name: Node Core

on:
  push:
    paths:
      - 'node-core/**'
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./node-core
          annotations: none
